[tool.poetry]
name = "villager"
version = "0.1.0"
description = ""
authors = ["danimal"]
packages = [
  { include = "villager", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
rapidfuzz = "^3.13.0"
unidecode = "^1.4.0"
typer = "^0.20.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-watch = "^4.2.0"
pycountry = "^24.6.1"
requests = "^2.32.4"
pympler = "^1.1"

[tool.poetry.scripts]
villager = 'villager.cli:app'